// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCayyqWG9AVIbVKqkewJB4y_NmGBoRskio',
    appId: '1:23491431483:web:3b94a368a56baa606d601e',
    messagingSenderId: '23491431483',
    projectId: 'cins467-truestory-29b3c',
    authDomain: 'cins467-truestory-29b3c.firebaseapp.com',
    storageBucket: 'cins467-truestory-29b3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1LMURMbOETJr2VUAdq1OA5wiRPc9_pKw',
    appId: '1:23491431483:android:c3c72c7b09d6e0086d601e',
    messagingSenderId: '23491431483',
    projectId: 'cins467-truestory-29b3c',
    storageBucket: 'cins467-truestory-29b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzmr3jrEvM08mwXBInHSSB7v9Tgt_gT0',
    appId: '1:23491431483:ios:b7f2596130638a1f6d601e',
    messagingSenderId: '23491431483',
    projectId: 'cins467-truestory-29b3c',
    storageBucket: 'cins467-truestory-29b3c.appspot.com',
    iosBundleId: 'com.example.truestoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzmr3jrEvM08mwXBInHSSB7v9Tgt_gT0',
    appId: '1:23491431483:ios:e70dbca08daf65866d601e',
    messagingSenderId: '23491431483',
    projectId: 'cins467-truestory-29b3c',
    storageBucket: 'cins467-truestory-29b3c.appspot.com',
    iosBundleId: 'com.example.truestoryApp.RunnerTests',
  );
}
